version: '3'

services:
  app:
    env_file:
      - .env
    container_name: geolocation-server
    restart: always
    build: .
    ports:
      - '$PORT:$PORT'
    depends_on:
      - postgres
    links:
      - postgres
    networks:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - .env
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
